# Generated by Django 4.1.1 on 2022-09-08 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('starting_item', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SituationVerbNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('get_item_bool', models.BooleanField(default=False)),
                ('required_item_bool', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('new_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_item_choices', to='remy_text_api.item')),
                ('noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remy_text_api.noun')),
                ('outcome_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_choices', to='remy_text_api.situation')),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_item_choices', to='remy_text_api.item')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_verb_nouns', to='remy_text_api.situation')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remy_text_api.verb')),
            ],
        ),
        migrations.CreateModel(
            name='GameFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_flags', to='remy_text_api.game')),
                ('situation_verb_noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_flags', to='remy_text_api.situationverbnoun')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='remy_text_api.situation'),
        ),
        migrations.AddField(
            model_name='game',
            name='items',
            field=models.ManyToManyField(related_name='games', to='remy_text_api.item'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
