# Generated by Django 4.1.1 on 2022-09-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationverbnoun',
            name='new_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_item_svns', to='remy_text_api.item'),
        ),
        migrations.AlterField(
            model_name='situationverbnoun',
            name='noun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svns', to='remy_text_api.noun'),
        ),
        migrations.AlterField(
            model_name='situationverbnoun',
            name='outcome_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_svns', to='remy_text_api.situation'),
        ),
        migrations.AlterField(
            model_name='situationverbnoun',
            name='required_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_item_svns', to='remy_text_api.item'),
        ),
        migrations.AlterField(
            model_name='situationverbnoun',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulting_svns', to='remy_text_api.situation'),
        ),
        migrations.AlterField(
            model_name='situationverbnoun',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svns', to='remy_text_api.verb'),
        ),
    ]
