# Generated by Django 4.1.1 on 2022-09-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0002_alter_situationverbnoun_new_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('get_item_bool', models.BooleanField(default=False)),
                ('required_item_bool', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('new_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_item_action', to='remy_text_api.item')),
                ('nouns', models.ManyToManyField(related_name='actions', to='remy_text_api.noun')),
                ('outcome_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_action', to='remy_text_api.situation')),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_item_action', to='remy_text_api.item')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulting_action', to='remy_text_api.situation')),
                ('verbs', models.ManyToManyField(related_name='actions', to='remy_text_api.verb')),
            ],
        ),
        migrations.RemoveField(
            model_name='gameflag',
            name='situation_verb_noun',
        ),
        migrations.DeleteModel(
            name='SituationVerbNoun',
        ),
        migrations.AddField(
            model_name='gameflag',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_flags', to='remy_text_api.action'),
        ),
    ]
