# Generated by Django 4.1.1 on 2022-09-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0003_action_remove_gameflag_situation_verb_noun_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='outcome_situation',
            new_name='new_situation',
        ),
        migrations.AddField(
            model_name='action',
            name='new_situation_bool',
            field=models.BooleanField(default=False),
        ),
    ]
