# Generated by Django 4.1.1 on 2022-09-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0004_rename_outcome_situation_action_new_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='disable_action_dependencies',
            field=models.ManyToManyField(related_name='disabled_actions', to='remy_text_api.action'),
        ),
        migrations.AddField(
            model_name='action',
            name='enable_action_dependencies',
            field=models.ManyToManyField(related_name='enabled_actions', to='remy_text_api.action'),
        ),
        migrations.AddField(
            model_name='action',
            name='lucidity_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='use_item',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='use_item_action', to='remy_text_api.item'),
        ),
        migrations.AddField(
            model_name='action',
            name='use_item_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='required_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_item_action', to='remy_text_api.item'),
        ),
    ]
