# Generated by Django 4.1.1 on 2022-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0007_remove_action_new_item_action_alt_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='display_response_on_complete',
            field=models.BooleanField(default=True),
        ),
    ]
