# Generated by Django 4.1.1 on 2022-09-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remy_text_api', '0008_action_display_response_on_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_item',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='remy_text_api.item'),
        ),
    ]
